export enum SocketEvent {
  CONNECT = 'connect',
  DISCONNECT = 'disconnect',
  ERROR = 'error',

  SD_STATUS = 'sd-status',
  GENERATE_IMAGE = 'generate-image',
  GENERATE_IMAGE_INTERRUPT = 'generate-image-interrupt',
  IMAGE_OUTPUT = 'image-output',
  FETCH_IMAGES = 'fetch-images',
  FETCH_IMAGES_MODAL = 'fetch-images-modal',
  REMOVE_IMAGE = 'remove-image',
  FETCH_SD_MODELS = 'fetch-sd-models',
  FETCH_UPSCALERS = 'fetch-upscalers',
  FETCH_SD_OPTIONS = 'fetch-sd-options',
  SET_SD_OPTIONS = 'set-sd-options',
  FETCH_SAMPLERS = 'fetch-samplers',
  FETCH_IMAGE_DATA = 'fetch-image-data',
  IMAGE_OUTPUT_BASE64 = 'image-output-base64',
  PROGRESS_IMAGE = 'progress-image',
  PROGRESS_ETA = 'progress-eta',
  PROGRESS_PERCENT = 'progress-percent',
  FETCH_OPTIMIZERS = 'fetch-optimizers',
  FETCH_VAES = 'fetch-vaes',

  LLM_COMPLETION = 'llm-completion',
  LLM_CHUNK = 'llm-chunk',
  LLM_DONE = 'llm-done',
}
